export const DUMMY_LIST_TOKENS = [
  {
    id: 1,
    pairName: "BTC/IDRX",
    latestPrice: "10,000.34",
    isFavorite: false,
    icon: "btc",
  },
  {
    id: 2,
    pairName: "ETH/IDRX",
    latestPrice: "2,845.67",
    isFavorite: true,
    icon: "eth",
  },
  {
    id: 3,
    pairName: "SOL/IDRX",
    latestPrice: "123.45",
    isFavorite: false,
    icon: "sol",
  },
  {
    id: 4,
    pairName: "ADA/IDRX",
    latestPrice: "0.56",
    isFavorite: true,
    icon: "ada",
  },
  {
    id: 5,
    pairName: "DOT/IDRX",
    latestPrice: "7.89",
    isFavorite: false,
    icon: "dot",
  },
  {
    id: 6,
    pairName: "XRP/IDRX",
    latestPrice: "0.78",
    isFavorite: true,
    icon: "xrp",
  },
  {
    id: 7,
    pairName: "AVAX/IDRX",
    latestPrice: "35.67",
    isFavorite: false,
    icon: "avax",
  },
  {
    id: 8,
    pairName: "MATIC/IDRX",
    latestPrice: "0.89",
    isFavorite: true,
    icon: "matic",
  },
  {
    id: 9,
    pairName: "LINK/IDRX",
    latestPrice: "15.23",
    isFavorite: false,
    icon: "link",
  },
  {
    id: 10,
    pairName: "UNI/IDRX",
    latestPrice: "5.67",
    isFavorite: true,
    icon: "uni",
  },
];
